# Generated by Django 3.1.7 on 2021-04-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0002_remove_donardetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donardetails',
            name='adharcard',
            field=models.CharField(max_length=10),
        ),
    ]
