# Generated by Django 3.1.7 on 2021-04-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0004_auto_20210421_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donardetails',
            old_name='bookingdate',
            new_name='dateofrecovery',
        ),
    ]
