# Generated by Django 3.1.7 on 2021-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdetails',
            fields=[
                ('patientid', models.CharField(default='', max_length=10000000, primary_key=True, serialize=False)),
                ('donarname', models.CharField(default='', max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('adharnumber', models.CharField(max_length=10)),
                ('doctorcasesheet', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(default='', max_length=200)),
                ('dateofregister', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
