# Generated by Django 3.1.7 on 2021-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='adharnumber',
            new_name='hospitalname',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='donarname',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patientname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
